---
title: "''Lee-Carter for Hearing Loss''"
author:
  - name: Dr. Marta Campi
  - name: Dr. Mareike Buhl 
date: "2023-04-12"
runtime: shiny
geometry: "left=0.1in,right=0.25in,top=0.5in,bottom=1in"
output: html_document
---

<style type="text/css">

.main-container {
  max-width: 1500px;
  margin-left: 0;
  margin-right: 2;
}

.shiny-frame {
  height: 2800px;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Lee-Carter for Hearing Loss Modeling



```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(purrr)
library(tidyverse)
library(stringr)
library(reshape2)
library(viridis)
library(ggpubr)
library(demography)
library(StMoMo)
library(fds)
library(tidyr)
library(viridis)
```

## Data Analysis


```{r, echo=FALSE}

###############################
# SET DIRECTORY AND READ FILE #
###############################

mydir<- "C:\\Users\\mcampi\\Desktop\\Hung_Joanna\\data\\"
mydir2<- "C:\\Users\\mcampi\\Desktop\\Hung_Joanna\\code\\"

source(paste(mydir2, "utils.R", sep = "")) 


data_ampl2 = readRDS( file= paste(mydir, "data_ampl2bis.rds", sep = ""))
data_ampl2 <- data_ampl2[data_ampl2$AGE <= 90, ]
data_ampl2 <- data_ampl2[data_ampl2$AGE >= 45, ]


ggplot(data_ampl2, aes(x = AGE)) +
  geom_histogram(binwidth = 1, 
                 fill = "skyblue",
                 color = "black", 
                 aes(y = ..count..)) +
  labs(title = "Age Distribution", 
       x = "Age", y = "Frequency") +
  theme_bw() +
  theme(plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),)
```
```{r, echo=FALSE}
data_ampl2$age_group2 <- cut(data_ampl2$AGE, breaks = seq(0, 100, by = 5), labels = FALSE,
                             include.lowest = TRUE)
data_ampl2$age_group2 <- factor(paste0((data_ampl2$age_group2 - 1) * 5, "-", (data_ampl2$age_group2) * 5))

data_ampl2$age_group3 <- cut(data_ampl2$AGE, breaks = seq(0, 100, by = 1), labels = FALSE,
                             include.lowest = TRUE)
data_ampl2$age_group3 <- factor(paste0((data_ampl2$age_group3 - 1) , "-", (data_ampl2$age_group3) ))


data_lee_carter = data_ampl2[,c(3,4,7:17,34,35,36)]

```


```{r, echo=FALSE}
##############
# PARAMETERS #
##############

hl_classes = levels(data_ampl2$Classification) # for age_group3 levels(data_ampl2$Classification)[-5]
n_hlclasses = length(hl_classes)

freq_vector = sapply(1:11, function(i) str_split(colnames(data_lee_carter)[2+i], "_")[[1]][2])
n_freq = length(freq_vector)

age_groups <- levels(data_lee_carter$age_group) #[-c(1,2,3,4,10:12)] #stability results
n_age_g = length(age_groups)

age_groups2 <- levels(data_lee_carter$age_group2)
n_age_g2 = length(age_groups2)

all_age_groups = levels(data_lee_carter$age_group3)
n_age_g3 = length(all_age_groups)

treshold_hearing_rate = c(25,30,35,40,45,50)
n_tresh = length(treshold_hearing_rate)

```



```{r}

ggplot(data_ampl2, aes(x = Classification, y = SRT)) +
  geom_boxplot(aes(fill = Classification), color = "black") +
  labs(title = "SRT Distribution by Classification", 
       x = "Classification", y = "SRT") +
  theme_bw() +
  theme(plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggplot(data_ampl2, aes(x = Classification, y = SNR)) +
  geom_boxplot(aes(fill = Classification), color = "black") +
  labs(title = "SRT Distribution by Classification", 
       x = "Classification", y = "SNR") +
  theme_bw() +
  theme(plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

```


```{r, echo=FALSE}

```


```{r, echo=FALSE}

```



```{r, echo=FALSE}

```


```{r, echo=FALSE}

```